server:
  port: 8002
spring:
  application:
    name: eureka-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    hostname: eureka.xufilebox.top
    ip-address: eureka.xufilebox.top
  client:
    service-url:
      defaultZone: http://eureka.xufilebox.top:8001/eureka/
  server:
    enable-self-preservation: false
