server:
  port: 8001
spring:
  application:
    name: eureka-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  server:
    enable-self-preservation: false

management:
  health:
    mail:
      enabled: false