spring:
  redis:
    database: 0
    pool:
      max-active: 8
      max-idle: 9
      max-wait: -1
      min-idle: 0
  redis-master:
    host: master.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  redis-slave1:
    host: slave1.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  redis-slave2:
    host: slave2.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://master.db.xufilebox.top:3306/filebox?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: rootpassword
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://slave1.db.xufilebox.top:3306/filebox?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: rootpassword
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_2:
          url: jdbc:mysql://slave2.db.xufilebox.top:3306/filebox?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: rootpassword
          driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: auth-service
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true
        service-id: config-service
#mapper plus
mybatis-plus:
  mapper-locations: classpath*:top/xufilebox/common/mybatis/mapper/*Mapper.xml


jwt:
  secret: filebox
  expiration: 86400
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service8002:8002/eureka/,http://eureka-service8001:8001/eureka/