spring:
  redis:
    database: 0
    pool:
      max-active: 8
      max-idle: 9
      max-wait: -1
      min-idle: 0
  redis-master:
    host: master.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  redis-slave1:
    host: slave1.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  redis-slave2:
    host: slave2.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  application:
    name: gateway-service
  cloud:
#    config:
#      profile: dev
#      label: master
#      discovery:
#        enabled: true
#        service-id: config-service
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
#          filters:
#            - StripPrefix=1

#mapper plus
mybatis-plus:
  mapper-locations: classpath*:top/xufilebox/common/mybatis/mapper/*Mapper.xml


jwt:
  secret: filebox
  expiration: 86400
  tokenHead: Bearer
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service8002:8002/eureka/, http://eureka-service8001:8001/eureka/
server:
  port: 8021

# 白名单， 用,分隔， 中间不可加空格
filebox:
  allowPaths: /auth/**