server:
  port: 8021
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8041
          predicates:
            - Path=/user/**
        - id: file-service
          uri: http://localhost:8181
          predicates:
            - Path=/file/**
  redis:
    database: 0
    pool:
      max-active: 8
      max-idle: 9
      max-wait: -1
      min-idle: 0
  redis-master:
    host: master.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  redis-slave1:
    host: slave1.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
  redis-slave2:
    host: slave2.redis.xufilebox.top
    port: 6379
    password:
    testOnBorrow: true
#mapper plus
mybatis-plus:
  mapper-locations: classpath*:top/xufilebox/common/mybatis/mapper/*Mapper.xml

jwt:
  secret: filebox
  expiration: 86400
  tokenHead: Bearer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka


# 白名单， 用,分隔， 中间不可加空格
filebox:
  allowPaths: /auth/**
logging:
  level:
    root: info